Repository streamnative/function-mesh-worker-service, pull requests merged in 2022-10, with the labels that each got.

#401 support logging configurations
  src/main/java/io/functionmesh/compute/models/CustomRuntimeOptions.java
  src/main/java/io/functionmesh/compute/util/FunctionsUtil.java
Labels: type/feature, doc-required, m/2022-10, need-cherry-pick/2.9.3, need-cherry-pick/2.10.1

#451 Fix function list return duplicate data error
  src/main/java/io/functionmesh/compute/rest/api/MeshComponentImpl.java
Labels: type/bug, m/2022-10

#456 Move auth no-related configs out of auth if statement
  src/main/java/io/functionmesh/compute/rest/api/FunctionsImpl.java
  src/main/java/io/functionmesh/compute/rest/api/SinksImpl.java
  src/main/java/io/functionmesh/compute/rest/api/SourcesImpl.java
Labels: type/enhancement, m/2022-11

#459 remove unused builtin connector yaml resource
  src/main/resources/connectors.yaml
Labels: type/task, doc-required, m/2022-11

#449 support windowConfig
  src/main/java/io/functionmesh/compute/models/CustomRuntimeOptions.java
  src/main/java/io/functionmesh/compute/util/FunctionsUtil.java
  src/test/java/io/functionmesh/compute/testdata/Generate.java
  src/test/java/io/functionmesh/compute/util/FunctionsUtilTest.java
Labels: type/feature, m/2022-11

#469 move integration kind cluster to v1.22.15
  .ci/helm.sh
  hack/common.sh
  hack/kind-cluster-build.sh
Labels: area/ci, type/bug

#471 Add jarfullname to function mesh connector definition
  src/main/java/io/functionmesh/compute/models/FunctionMeshConnectorDefinition.java
  src/test/java/io/functionmesh/compute/models/FunctionMeshConnectorDefinitionTest.java
Labels: type/enhancement, doc-required, m/2022-11, ready-to-review
