Repository streamnative/function-mesh-worker-service, pull requests merged in 2022-12, with the labels that each got.

#513 Support java opts
  src/main/java/io/functionmesh/compute/models/MeshWorkerServiceCustomConfig.java
  src/main/java/io/functionmesh/compute/util/FunctionsUtil.java
  src/main/java/io/functionmesh/compute/util/SinksUtil.java
  src/main/java/io/functionmesh/compute/util/SourcesUtil.java
Labels: doc-required

#537 Support token authentication
  .ci/clusters/values_mesh_worker_service_with_jwt.yaml
  .github/workflows/test-integration-mesh-worker-service-with-jwt.yml
  scripts/set-pulsar-version.sh
  src/main/java/io/functionmesh/compute/auth/AuthHandler.java
  src/main/java/io/functionmesh/compute/auth/AuthHandlerInsecure.java
  src/main/java/io/functionmesh/compute/auth/AuthHandlerJWTToken.java
  src/main/java/io/functionmesh/compute/rest/api/MeshComponentImpl.java
  src/main/java/io/functionmesh/compute/util/CommonUtil.java
Labels: type/enhancement, m/2022-12

#547 Change workflow to pull_request_target
  .github/workflows/test-integration-mesh-worker-service-with-jwt.yml
Labels: area/ci, type/bug, m/2022-12

#549 verify function mesh 0.9.0
  pom.xml
Labels: area/ci, type/task, m/2022-12
