Repository streamnative/function-mesh-worker-service, pull requests merged in 2022-09, with the labels that each got.

#362 improve label
  src/main/java/io/functionmesh/compute/rest/api/MeshComponentImpl.java
  src/main/java/io/functionmesh/compute/util/CommonUtil.java
Labels: type/enhancement, m/2022-09

#366 bump kubernetes client to fix vulnerability
  pom.xml
Labels: type/enhancement, m/2022-09

#370 use jdk17 in branch-2.11
  .ci/clusters/values_mesh_worker_service.yaml
  .ci/clusters/values_mesh_worker_service_with_oauth.yaml
  .github/workflows/project.yml
  .github/workflows/test-integration-mesh-worker-service-with-oauth.yml
  .github/workflows/test-integration-mesh-worker-service.yml
  integration-tests/docker/connectors.yaml
  pom.xml
  src/main/java/io/functionmesh/compute/MeshWorker.java
  src/main/java/io/functionmesh/compute/auth/AuthHandler.java
  src/main/java/io/functionmesh/compute/auth/AuthHandlerOauth.java
  src/main/java/io/functionmesh/compute/rest/api/FunctionsImpl.java
  src/main/java/io/functionmesh/compute/rest/api/MeshComponentImpl.java
  src/main/java/io/functionmesh/compute/rest/api/SinksImpl.java
  src/main/java/io/functionmesh/compute/rest/api/SourcesImpl.java
  src/main/java/io/functionmesh/compute/util/CommonUtil.java
  src/main/java/io/functionmesh/compute/util/FunctionsUtil.java
  src/test/java/io/functionmesh/compute/util/SinksUtilTest.java
Labels: type/enhancement, m/2022-09

#382 remove tmate and use the ssh access script from pulsar repo
  .github/actions/ssh-access/action.yml
  .github/actions/tune-runner-vm/action.yml
  .github/workflows/test-integration-mesh-worker-service-with-oauth.yml
  .github/workflows/test-integration-mesh-worker-service.yml
Labels: m/2022-09

#384 fix builtin connector with imageRegistry
  integration-tests/docker/connectors.yaml
  src/main/java/io/functionmesh/compute/models/FunctionMeshConnectorDefinition.java
Labels: m/2022-09

#396 bump to 0.6.0
  pom.xml
Labels: m/2022-09

#379 Remove oauth2.jar
  .github/workflows/test-integration-mesh-worker-service-with-oauth.yml
  .github/workflows/test-integration-mesh-worker-service.yml
  integration-tests/docker/Dockerfile
  integration-tests/docker/pulsar-broker-auth-oauth2.jar
Labels: type/enhancement, m/2022-10

#415 fix doc content
  src/main/java/io/functionmesh/compute/models/MeshWorkerServiceCustomConfig.java
Labels: doc, m/2022-10

#426 [worker-service-159] support volume and volumeMounts
  src/main/java/io/functionmesh/compute/rest/api/FunctionsImpl.java
  src/main/java/io/functionmesh/compute/rest/api/SinksImpl.java
  src/main/java/io/functionmesh/compute/rest/api/SourcesImpl.java
  src/main/java/io/functionmesh/compute/util/FunctionsUtil.java
  src/main/java/io/functionmesh/compute/util/SinksUtil.java
  src/main/java/io/functionmesh/compute/util/SourcesUtil.java
  src/test/java/io/functionmesh/compute/util/FunctionsUtilTest.java
  src/test/java/io/functionmesh/compute/util/SinksUtilTest.java
  src/test/java/io/functionmesh/compute/util/SourcesUtilTest.java
Labels: type/bug, m/2022-10
