Repository streamnative/function-mesh-worker-service, pull requests merged in 2022-07, with the labels that each got.

#290 change docker registry from docker.pkg.github.com to ghcr.io
  .github/workflows/project.yml
  .github/workflows/test-integration-mesh-worker-service.yml
  README.md
  scripts/build.sh
  scripts/crd-model-gen/Dockerfile
  scripts/generate-crd.sh
Labels: area/ci, type/enhancement, m/2022-07

#293 fix ci test false postive
  src/main/java/io/functionmesh/compute/annotation/TrustedModeOnly.java
  src/test/java/io/functionmesh/compute/rest/api/FunctionImplV2Test.java
Labels: area/ci, type/bug

#299 Support unmanaged resource
  src/main/java/io/functionmesh/compute/models/CustomRuntimeOptions.java
  src/main/java/io/functionmesh/compute/util/CommonUtil.java
  src/main/java/io/functionmesh/compute/util/FunctionsUtil.java
  src/main/java/io/functionmesh/compute/util/SinksUtil.java
  src/main/java/io/functionmesh/compute/util/SourcesUtil.java
  src/test/java/io/functionmesh/compute/rest/api/SinksImpTest.java
  src/test/java/io/functionmesh/compute/rest/api/SourcesImpTest.java
Labels: type/enhancement, doc-required, m/2022-07

#310 Make it able to config out-of-cluster k8s client
  src/main/java/io/functionmesh/compute/MeshWorkerService.java
Labels: type/feature, doc-required, m/2022-07

#316 temp reduce the disk usage in ci
  .ci/clusters/values_mesh_worker_service.yaml
  scripts/generate-crd.sh
Labels: area/ci, type/bug

#325 use v1.8.2 cert-manager
  .ci/helm.sh
Labels: area/ci, type/bug
