Repository streamnative/function-mesh-worker-service, pull requests merged in 2023-01, with the labels that each got.

#575 Check FunctionMesh when init
  .ci/deploy_pulsar_cluster.sh
  src/main/java/io/functionmesh/compute/MeshWorkerService.java
Labels: type/enhancement, m/2023-01

#554 support hpa strategies
  pom.xml
  src/main/java/io/functionmesh/compute/models/CustomRuntimeOptions.java
  src/main/java/io/functionmesh/compute/models/HPASpec.java
  src/main/java/io/functionmesh/compute/util/CommonUtil.java
  src/main/java/io/functionmesh/compute/util/FunctionsUtil.java
  src/main/java/io/functionmesh/compute/util/SinksUtil.java
  src/main/java/io/functionmesh/compute/util/SourcesUtil.java
  src/test/java/io/functionmesh/compute/rest/api/FunctionImplV2Test.java
  src/test/java/io/functionmesh/compute/rest/api/SinksImplV2Test.java
  src/test/java/io/functionmesh/compute/rest/api/SourcesImplV2Test.java
Labels: type/feature, doc-required, m/2023-01

#618 Support hot-reloading built-in connectors when the config file changes
  src/main/java/io/functionmesh/compute/MeshWorkerService.java
  src/main/java/io/functionmesh/compute/models/MeshWorkerServiceCustomConfig.java
  src/main/java/io/functionmesh/compute/worker/MeshConnectorsManager.java
  src/test/java/io/functionmesh/compute/util/WorkerConfigTest.java
  src/test/resources/test_worker_config.yaml
Labels: type/enhancement, compute/serverless
