Repository streamnative/function-mesh-worker-service, pull requests merged in 2023-06, with the labels that each got.

#799 Fix restartFunctions and enhance ci
  .ci/clusters/values_mesh_worker_service_with_insecure_auth.yaml
  .ci/clusters/values_mesh_worker_service_with_jwt.yaml
  .ci/clusters/values_mesh_worker_service_with_oauth.yaml
  .ci/helm.sh
  .ci/verify_mesh_worker_service.sh
  .ci/verify_package_management_service_with_auth.sh
  .github/workflows/test-integration-mesh-worker-service-with-jwt.yml
  src/main/java/io/functionmesh/compute/rest/api/FunctionsImpl.java
  src/main/java/io/functionmesh/compute/rest/api/SinksImpl.java
  src/main/java/io/functionmesh/compute/rest/api/SourcesImpl.java
Labels: type/enhancement, m/2023-06

#797 Implement trigger
  .ci/helm.sh
  src/main/java/io/functionmesh/compute/MeshWorkerService.java
  src/main/java/io/functionmesh/compute/rest/api/MeshComponentImpl.java
Labels: type/feature, m/2023-06

#810 fix Not enough non-faulty bookies available
  .ci/clusters/values_mesh_worker_service.yaml
  .ci/clusters/values_mesh_worker_service_with_insecure_auth.yaml
  .ci/clusters/values_mesh_worker_service_with_jwt.yaml
  .ci/clusters/values_mesh_worker_service_with_oauth.yaml
Labels: area/ci, type/bug, m/2023-06
